//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ANEO_Banking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACCOUNTS
    {
        public ACCOUNTS()
        {
            this.CUSTOMER_CREDIT_CARDS = new HashSet<CUSTOMER_CREDIT_CARDS>();
            this.OPTIONS = new HashSet<OPTIONS>();
            this.TRANSACTIONS = new HashSet<TRANSACTIONS>();
            this.TRANSACTIONS1 = new HashSet<TRANSACTIONS>();
        }
    
        public string ACCOUNT_NUMBER { get; set; }
        public Nullable<decimal> BALANCE { get; set; }
        public Nullable<System.DateTime> CREATED_AT { get; set; }
        public Nullable<System.DateTime> UPDATED_AT { get; set; }
    
        public virtual ICollection<CUSTOMER_CREDIT_CARDS> CUSTOMER_CREDIT_CARDS { get; set; }
        public virtual ICollection<OPTIONS> OPTIONS { get; set; }
        public virtual ICollection<TRANSACTIONS> TRANSACTIONS { get; set; }
        public virtual ICollection<TRANSACTIONS> TRANSACTIONS1 { get; set; }
    }
}
