//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ANEO_Banking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CREDIT_CARDS
    {
        public CREDIT_CARDS()
        {
            this.CUSTOMER_CREDIT_CARDS = new HashSet<CUSTOMER_CREDIT_CARDS>();
        }
    
        public string CARD_NUMBER { get; set; }
        public Nullable<System.DateTime> EXPIRE_DATE { get; set; }
        public string CVV { get; set; }
        public Nullable<System.DateTime> CREATED_AT { get; set; }
        public Nullable<System.DateTime> UPDATED_AT { get; set; }
    
        public virtual ICollection<CUSTOMER_CREDIT_CARDS> CUSTOMER_CREDIT_CARDS { get; set; }
    }
}
