//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ANEO_Banking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMER_CREDIT_CARDS
    {
        public decimal ID { get; set; }
        public decimal ID_CUSTOMER { get; set; }
        public string CARD_NUMBER { get; set; }
        public string ACCOUNT_NUMBER { get; set; }
        public Nullable<System.DateTime> CREATED_AT { get; set; }
        public Nullable<System.DateTime> UPDATED_AT { get; set; }
    
        public virtual ACCOUNTS ACCOUNTS { get; set; }
        public virtual CREDIT_CARDS CREDIT_CARDS { get; set; }
        public virtual CUSTOMERS CUSTOMERS { get; set; }
    }
}
