//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ANEO_Banking.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ACCOUNTS> ACCOUNTS { get; set; }
        public DbSet<CREDIT_CARDS> CREDIT_CARDS { get; set; }
        public DbSet<CUSTOMER_CREDIT_CARDS> CUSTOMER_CREDIT_CARDS { get; set; }
        public DbSet<CUSTOMERS> CUSTOMERS { get; set; }
        public DbSet<OPTIONS> OPTIONS { get; set; }
        public DbSet<PACKS> PACKS { get; set; }
        public DbSet<TRANSACTIONS> TRANSACTIONS { get; set; }
        public DbSet<TRANSACTIONS_HISTORY> TRANSACTIONS_HISTORY { get; set; }
    }
}
