//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ANEO_Banking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PACKS
    {
        public PACKS()
        {
            this.OPTIONS = new HashSet<OPTIONS>();
        }
    
        public decimal ID { get; set; }
        public string TYPE { get; set; }
        public Nullable<decimal> COST { get; set; }
        public Nullable<System.DateTime> CREATED_AT { get; set; }
        public Nullable<System.DateTime> UPDATED_AT { get; set; }
    
        public virtual ICollection<OPTIONS> OPTIONS { get; set; }
    }
}
