//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ANEO_Banking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSACTIONS
    {
        public decimal ID { get; set; }
        public string ACC_NO_CUSTOMER1 { get; set; }
        public string ACC_NO_CUSTOMER2 { get; set; }
    
        public virtual ACCOUNTS ACCOUNTS { get; set; }
        public virtual ACCOUNTS ACCOUNTS1 { get; set; }
        public virtual TRANSACTIONS_HISTORY TRANSACTIONS_HISTORY { get; set; }
    }
}
