
--
-- ACCOUNTS
--
  CREATE TABLE "ACCOUNTS" 
   (	"ACCOUNT_NUMBER" VARCHAR2(24) NOT NULL ENABLE,
	"BALANCE" FLOAT(126),
	"CREATED_AT" DATE,
	"UPDATED_AT" DATE,
	PRIMARY KEY ("ACCOUNT_NUMBER") ENABLE
   );
--
-- CREDIT_CARDS
--
  CREATE TABLE "CREDIT_CARDS" 
   (	"CARD_NUMBER" VARCHAR2(16) NOT NULL ENABLE,
	"EXPIRE_DATE" DATE,
	"CVV" VARCHAR2(3),
	"CREATED_AT" DATE,
	"UPDATED_AT" DATE,
	PRIMARY KEY ("CARD_NUMBER") ENABLE
   );
--
-- CUSTOMER_CREDIT_CARDS
--
  CREATE TABLE "CUSTOMER_CREDIT_CARDS" 
   (	"ID" NUMBER(*,0) NOT NULL ENABLE,
	"ID_CUSTOMER" NUMBER(*,0) NOT NULL ENABLE,
	"CARD_NUMBER" VARCHAR2(16) NOT NULL ENABLE,
	"ACCOUNT_NUMBER" VARCHAR2(24) NOT NULL ENABLE,
	"CREATED_AT" DATE,
	"UPDATED_AT" DATE,
	PRIMARY KEY ("ID") ENABLE
   );
--
-- CUSTOMERS
--
  CREATE TABLE "CUSTOMERS" 
   (	"ID" NUMBER(*,0) NOT NULL ENABLE,
	"NUME" VARCHAR2(15) NOT NULL ENABLE,
	"PRENUME" VARCHAR2(30) NOT NULL ENABLE,
	"CREATED_AT" DATE,
	"UPDATED_AT" DATE,
	PRIMARY KEY ("ID") ENABLE
   );
--
-- OPTIONS
--
  CREATE TABLE "OPTIONS" 
   (	"ID" NUMBER(*,0) NOT NULL ENABLE,
	"ACCOUNT_NUMBER" VARCHAR2(24) NOT NULL ENABLE,
	"ID_PACKAGE" NUMBER(*,0) NOT NULL ENABLE,
	"CREATED_AT" DATE,
	"UPDATED_AT" DATE,
	PRIMARY KEY ("ID") ENABLE
   );
--
-- PACKS
--
  CREATE TABLE "PACKS" 
   (	"ID" NUMBER(*,0) NOT NULL ENABLE,
	"TYPE" VARCHAR2(15),
	"COST" NUMBER(*,0),
	"CREATED_AT" DATE,
	"UPDATED_AT" DATE,
	PRIMARY KEY ("ID") ENABLE
   );
--
-- TRANSACTIONS
--
  CREATE TABLE "TRANSACTIONS" 
   (	"ID" NUMBER(*,0) NOT NULL ENABLE,
	"ACC_NO_CUSTOMER1" VARCHAR2(24) NOT NULL ENABLE,
	"ACC_NO_CUSTOMER2" VARCHAR2(24) NOT NULL ENABLE,
	PRIMARY KEY ("ID") ENABLE
   );
--
-- TRANSACTIONS_HISTORY
--
  CREATE TABLE "TRANSACTIONS_HISTORY" 
   (	"ID_TRANSACTION" NUMBER(*,0) NOT NULL ENABLE,
	"AMOUNT" NUMBER(*,0),
	"CREATED_AT" DATE,
	"UPDATED_AT" DATE,
	PRIMARY KEY ("ID_TRANSACTION") ENABLE
   );
--
-- FK_CUST_CRED_CARDS_ACC_NUM
--
ALTER TABLE "CUSTOMER_CREDIT_CARDS" ADD CONSTRAINT "FK_CUST_CRED_CARDS_ACC_NUM" FOREIGN KEY ("ACCOUNT_NUMBER") REFERENCES "ACCOUNTS"("ACCOUNT_NUMBER") ENABLE;

--
-- FK_CUST_CRED_CARDS_CARD_NUM
--
ALTER TABLE "CUSTOMER_CREDIT_CARDS" ADD CONSTRAINT "FK_CUST_CRED_CARDS_CARD_NUM" FOREIGN KEY ("CARD_NUMBER") REFERENCES "CREDIT_CARDS"("CARD_NUMBER") ENABLE;

--
-- FK_CUST_CRED_CARDS_ID_CUST
--
ALTER TABLE "CUSTOMER_CREDIT_CARDS" ADD CONSTRAINT "FK_CUST_CRED_CARDS_ID_CUST" FOREIGN KEY ("ID_CUSTOMER") REFERENCES "CUSTOMERS"("ID") ENABLE;

--
-- FK_OPTIONS_ACCOUNT_NUMBER
--
ALTER TABLE "OPTIONS" ADD CONSTRAINT "FK_OPTIONS_ACCOUNT_NUMBER" FOREIGN KEY ("ACCOUNT_NUMBER") REFERENCES "ACCOUNTS"("ACCOUNT_NUMBER") ENABLE;

--
-- FK_OPTIONS_ID_PACKAGE
--
ALTER TABLE "OPTIONS" ADD CONSTRAINT "FK_OPTIONS_ID_PACKAGE" FOREIGN KEY ("ID_PACKAGE") REFERENCES "PACKS"("ID") ENABLE;

--
-- FK_TRANS_ACC_NO_CUS1
--
ALTER TABLE "TRANSACTIONS" ADD CONSTRAINT "FK_TRANS_ACC_NO_CUS1" FOREIGN KEY ("ACC_NO_CUSTOMER1") REFERENCES "ACCOUNTS"("ACCOUNT_NUMBER") ENABLE;

--
-- FK_TRANS_ACC_NO_CUS2
--
ALTER TABLE "TRANSACTIONS" ADD CONSTRAINT "FK_TRANS_ACC_NO_CUS2" FOREIGN KEY ("ACC_NO_CUSTOMER2") REFERENCES "ACCOUNTS"("ACCOUNT_NUMBER") ENABLE;

--
-- FK_TRANS_HISTORY_ID_TRANS
--
ALTER TABLE "TRANSACTIONS_HISTORY" ADD CONSTRAINT "FK_TRANS_HISTORY_ID_TRANS" FOREIGN KEY ("ID_TRANSACTION") REFERENCES "TRANSACTIONS"("ID") ENABLE;

